"""add_created_at_to_vehicle

Revision ID: 2932bbb5f318
Revises: 0ddabfce247b
Create Date: 2026-08-07 14:39:54.515805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2932bbb5f318'
down_revision: Union[str, Sequence[str], None] = '0ddabfce247b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_details', 'created_at')
    # ### end Alembic commands ###
