"""Create uploaded_images table

Revision ID: 3519f12d02ee
Revises: b019eacf5970
Create Date: 2026-07-13 12:03:04.207402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3519f12d02ee'
down_revision: Union[str, Sequence[str], None] = 'b019eacf5970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=True),
    sa.Column('ocr_text', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_images_id'), 'uploaded_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_images_id'), table_name='uploaded_images')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
