"""Initial schema

Revision ID: 9944ae2476ae
Revises: 
Create Date: 2026-07-24 16:21:27.613167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9944ae2476ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=True),
    sa.Column('ocr_text', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_images_id'), 'uploaded_images', ['id'], unique=False)
    op.create_table('vehicle_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_no')
    )
    op.create_index(op.f('ix_vehicle_details_id'), 'vehicle_details', ['id'], unique=False)
    op.create_table('gate_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_pass_no', sa.String(length=30), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('entry_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_pass_no')
    )
    op.create_index(op.f('ix_gate_pass_id'), 'gate_pass', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_pass_id'), table_name='gate_pass')
    op.drop_table('gate_pass')
    op.drop_index(op.f('ix_vehicle_details_id'), table_name='vehicle_details')
    op.drop_table('vehicle_details')
    op.drop_index(op.f('ix_uploaded_images_id'), table_name='uploaded_images')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
