"""Expand vehicle model

Revision ID: 045263d10390
Revises: 86d46358dea9
Create Date: 2026-07-13 16:04:56.453332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045263d10390'
down_revision: Union[str, Sequence[str], None] = '86d46358dea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('vehicle_details', sa.Column('color', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_details', 'color')
    op.drop_column('vehicle_details', 'manufacturer')
    # ### end Alembic commands ###
