"""Add company and vehicle type

Revision ID: 86d46358dea9
Revises: 3519f12d02ee
Create Date: 2026-07-13 16:01:58.516041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d46358dea9'
down_revision: Union[str, Sequence[str], None] = '3519f12d02ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.add_column('vehicle_details', sa.Column('vehicle_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_details', 'vehicle_type')
    op.drop_column('vehicle_details', 'company_name')
    # ### end Alembic commands ###
